spring:
  profiles:
    active:
    - local

---
spring:
  profiles:
  - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"

  datasource:
    url: jdbc:mariadb://localhost:3306/Lcomputer?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    jdbc:
      initialize-schema: always

  devtools:
    livereload:
      enabled: true
      
server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:
        development: true
    session:
      timeout: 7200
  error:
    whitelabel:
      enabled: false
      
mybatis:
  type-aliases-package: com.fileuploadvue.example.vo
  mapper-locations:
  - mapper/**/*.xml